### ISSUE TITLE
Use backlight instead of setting it?

### ISSUE THREAD

**Issue by mhvk** [Redsandro/thinkpad-x1-yoga#1]
@Redsandro - I found your nice script and starting using it for my X1 Yoga, but then noticed that at least under KDE, the OSD display sometimes does not quite follow the brightness. I though it might be simpler to just let KDE adjust the "backlight" and then adjust the brightness in xrandr accordingly. This is done with the following revised `oled-backlight.sh`; if you think this is an improvement, I'm happy to make a PR.
```
#!/bin/bash
export XAUTHORITY=/home/mhvk/.Xauthority
export DISPLAY=:0.0

DISP_ID=eDP-1

# Get the current software brightness from xrandr. 
OLED_BR=`xrandr --verbose | grep -m 1 -i brightness | cut -f2 -d ' '`

# Get brightness from "backlight" (which gets adjusted by the window
# manager, but does nothing for an OLED display; we do this second,
# so that there has been time to adjust it).
BACKLIGHT="/sys/class/backlight/intel_backlight"
BRIGHTNESS=$(cat $BACKLIGHT/brightness)
MAX_BRIGHTNESS=$(cat $BACKLIGHT/max_brightness)

# Adjust current to desired brightness in 5 steps, using rounded percentages.
CURRENT=`LC_ALL=C /usr/bin/printf "%.*f" 2 $OLED_BR`
DESIRED=`echo "scale=2; $BRIGHTNESS / $MAX_BRIGHTNESS" | bc`
for I in {1..5..1}; do
    brightness=`echo "scale=2; $CURRENT + $I/5*($DESIRED-$CURRENT)" | bc`
    xrandr --output $DISP_ID --brightness $brightness 2>&1 >/dev/null | logger -t oled-brightness
done
```

**Comment by Redsandro** [comment]
Hi @mhvk thanks for letting me know.

Although your script is too different from [oled-brightness.sh](https://github.com/Redsandro/thinkpad-x1-yoga/blob/master/roles/display/files/oled-brightness.sh) to quickly spot the difference, I think I see what you're doing. I tried something like this initially, but the values seem to get out of sync in Cinnamon, so I needed to do it the other way around. Also I prefer the enhancements I built in:

* 12 or 15 brightness steps in stead of the Cinnamon default of 8 steps
* OLED can go above 1.0, (this is similar to the audio volume that can go up to 150%) a good default maximum is 1.2 or 1.4. (My script has it set to 1.2 so there won't be too much clipping but is an ideal maximum for using the laptop outside in the sun.)
* 10-step smooth transition in stead of 5 step.

I'd be interested in a solution based on and close to the original script, keeping the existing functionality, but with added lines to make it play nice with the the KDE OSD. I haven't given this further thought yet. Right now I'm in holiday-mode. Also I'm waiting for 18.04 (LTS) to revisit everything (although I'm hoping Gnome and Cinnamon will have OLED brightness fixed by then :crossed_fingers: )

**Comment by Redsandro** [comment]
We might be able to make a switch in updating the intel driver or not using `$DESKTOP_SESSION`. For Cinnamon the value is `cinnamon`. For future reference, what is the session name for KDE? (I don't use KDE).

**Comment by mhvk** [comment]
May be an idea; for KDE:
```
echo $DESKTOP_SESSION
/usr/share/xsessions/plasma
```

**Comment by mhvk** [comment]
@Redsandro - on the larger question, I indeed hope that lenovo/intel get there act together and make this script unnecessary (though I like the smooth transition...). I also considered trying to hook into the keypress events in the desktop manager itself (since the current linux procedure seems to be to turn acpi events into key events), but at least in KDE it seemed hard to hook into the brightness system that way.

Anyway, for now brightness works.
