### ISSUE TITLE
Bricked my system; stuck in low-graphics mode

### ISSUE THREAD

**Issue by thebalaa** [Redsandro/thinkpad-x1-yoga#2]
Applying the ansible playbook on x1 yoga second gen after doing clean install of Ubuntu 16.04.3 bricked my system :(

**Comment by Redsandro** [comment]
It happens sometimes due to unexpected package updates or other incompatibilities. You might want to try:
1. Start with an older kernel
2. Remove hwe kernels
3. Uninstall the `tlp` package.

Other than that, you're probably going to want to revert every role manually to find out which one breaks the system. It might help to see which tags you used and which tags were skipped to find out what caused the incompatibility so that we can prevent this from happening in the future.

If everything fails, I'm afraid you'll need to reinstall Ubuntu from scratch. :( But I've never seen a problem that can't be reverted.

Please note that I only tested an early version on Ubuntu; this is used and tested on Linux Mint 18.3. Also see the disclaimer:

> Use at your own risk. For advanced users only. Inspect the source before using. Worst case scenario: If something is conflicting or incompatible with your environment, your display manager might fail. You might have to log into textmode and undo related things.

**Comment by Redsandro** [comment]
Was fixed in [this PR](https://github.com/Redsandro/thinkpad-x1-yoga/commit/8bde9cd8a748897cb95748974d2dd8b3df0f9a4d) 6 months ago. Forgot to close issue.
